---
- hosts: web
  tasks:
    - name: install apache2
      apt: 
        name: apache2
    - name: start apache2
      service: 
        name: apache2  
        state: started
    - name: Use personal index.html usando jinja
      template:
        src: templates/index.html.js
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0644'